server:
  port: ""
  mode: "debug"

allowed_origins:

database:
  mongodb:
    host: "localhost"
    port: "27017"
    username: ""
    password: ""
    dbname: ""
    authSource: "admin"
  postgresql:
    host: ""
    port: ""
    username: ""
    password: ""
    dbname: ""

jwt:
  access_token:
    secret: ""
    expire_hours: ""
  refresh_token:
    secret: ""
    expire_hours: ""