server:
  port: ""
  mode: "debug"

allowed_origins:

database:
  type: "mongodb"
  mongodb:
    host: "localhost"
    port: "27017"
    username: ""
    password: ""
    dbname: ""
    authSource: "admin"

jwt:
  access_token:
    secret: ""
    expire_hours: ""
  refresh_token:
    secret: ""
    expire_hours: ""