server:
  port: "8080"
  mode: "debug" # Gin 模式: "debug", "release"

database:
  type: "mongodb"  # 資料庫類型

  mongodb:
    host: "localhost"
    port: "27017"
    username: "admin"
    password: "password"
    dbname: ""
    authSource: "admin"  # 用於使用者認證資料庫

  mysql:
    host: "localhost"
    port: "3306"
    username: "root"
    password: "password"
    dbname: ""

  postgresql:
    host: "localhost"
    port: "5432"
    username: "postgres"
    password: "password"
    dbname: ""

jwt:
  secret: ""
  expire_hours: ""